name: Publish Release

on:
  push:
    tags:
      - v*

jobs:
  build-and-deploy:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Install Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: "14.17.5"

      - name: Install Dependencies
        run: npm install

      - name: Build App
        run: npm run package
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Archive Release
        run: npm run make

#       - name: upload artifacts
#         uses: actions/upload-artifact@v3.0.0
#         with:
#           name: macOS-latest
#           path: out/make/zip/darwin/x86/pdf-watermark-*.zip

      - name: Release
        uses: softprops/action-gh-release@v0.1.14
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: out/make/zip/darwin/x64/pdf-watermark-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
